### Create Pantry
POST http://localhost:3000/api/pantry/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJpYXQiOjE3NjEwMTk3NzIsImV4cCI6MTc2MzYxMTc3Mn0.6u-o15-UR7BYFNY2X8TF0vxQFigX-cVZyCgNtHOTQo4
Content-Type: application/json

{
    "name" : "New Pantry"
}

### Get all pantries for a user
GET http://localhost:3000/api/pantry/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJpYXQiOjE3NjEwMTk3NzIsImV4cCI6MTc2MzYxMTc3Mn0.6u-o15-UR7BYFNY2X8TF0vxQFigX-cVZyCgNtHOTQo4

### Get pantry
GET http://localhost:3000/api/pantry/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJpYXQiOjE3NjEwMTk3NzIsImV4cCI6MTc2MzYxMTc3Mn0.6u-o15-UR7BYFNY2X8TF0vxQFigX-cVZyCgNtHOTQo4

